/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        // Supabase Storage bucket serving vehicle photos (FR-09) and
        // rental agreement PDFs generated by @react-pdf/renderer (A-02 Step 8)
        hostname: "*.supabase.co",
      },
    ],
  },
};

export default nextConfig;
